// Code generated by protoc-gen-go-cowsay. DO NOT EDIT.

package example

// "protoc-gen-go-cowsay/api/example"

func (x *Hello) Cowsay() string {
	say, _ := cowsay.Say(
		cowsay.Type("default"),
		cowsay.BallonWidth(40),
	)
	return say
}
