// Code generated by protoc-gen-go-cowsay. DO NOT EDIT.
//
// ImportPath: "protoc-gen-go-cowsay/api/example"

package example

import (
	v2 "github.com/Code-Hex/Neo-cowsay/v2"
)

var _ = v2.InDirectory

func (x *Hello) Cowsay() string {
	say, _ := v2.Say(x.GetGreeting())
	return say
}
