package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_cowsay.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-cowsay. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P("// ", file.GoImportPath)
	g.P()

	for _, msg := range file.Messages {
		g.P("func (x *", msg.GoIdent, ") Cowsay() string {")
		g.P("say, _ :=  cowsay.Say(")
		g.P("cowsay.Type(\"default\"),")
		g.P("cowsay.BallonWidth(40),")
		g.P(")")
		g.P("return say")
		g.P("}")
	}
}
