package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

const (
	cowsayPackage = protogen.GoImportPath("github.com/Code-Hex/Neo-cowsay/v2")
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_cowsay.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-cowsay. DO NOT EDIT.")
	g.P("//")
	g.P("// ImportPath: ", file.GoImportPath)
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	g.P("var _ = ", cowsayPackage.Ident("InDirectory"))

	for _, msg := range file.Messages {
		g.P("func (x *", msg.GoIdent, ") Cowsay() string {")
		g.P("say, _ :=  ", cowsayPackage.Ident("Say"), "(x.GetGreeting())")
		g.P("return say")
		g.P("}")
	}
}
